name: Run test

on:
  push:
    paths:
      - "**/*.c"
      - "**/*.h"
      - "auto/**"
      - "!*.md"
      - "!CHANGES*"
      - "!LICENSE"
      - "!.hgtags"
      - "!.clang-format"
      - "!.gitignore"
      - "!conf/**"
  workflow_dispatch:

jobs:
  run_test:
    strategy:
      fail-fast: false
      matrix:
        v: [
          { remote_port: "443", dig_type: "A", remote_host: "", remote_resolve: "" },
          { remote_port: "443", dig_type: "A", remote_host: "", remote_resolve: "remote_resolve" },
          { remote_port: "443", dig_type: "AAAA", remote_host: "", remote_resolve: "" },
          { remote_port: "443", dig_type: "AAAA", remote_host: "", remote_resolve: "remote_resolve" },
          { remote_port: "", dig_type: "", remote_host: "icanhazip.com:443", remote_resolve: "remote_resolve" },
          { remote_port: "", dig_type: "", remote_host: "icanhazip.com:443", remote_resolve: "" }
        ]
    uses: ./.github/workflows/test.yml
    with:
      remote_port: ${{ matrix.v.remote_port }}
      dig_type: ${{ matrix.v.dig_type }}
      remote_host: ${{ matrix.v.remote_host }}
      remote_resolve: ${{ matrix.v.remote_resolve }}