name: Run test

on:
  push:
    paths:
      - "**/*.c"
      - "**/*.h"
      - "auto/**"
      - "!*.md"
      - "!CHANGES*"
      - "!LICENSE"
      - "!.hgtags"
      - "!.clang-format"
      - "!.gitignore"
      - "!conf/**"
    branches:
      - master
  workflow_dispatch:

jobs:
  run_test:
    name: Run test (Remote Port ${{ matrix.remote_port }}) (Dig type ${{ matrix.dig_type }}) (Remote Host ${{ matrix.remote_host }}) (Remote resolve ${{ matrix.remote_resolve }})"
    permissions:
      contents: read
      packages: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - remote_port: "443"
            dig_type: "A"
            remote_host: ""
            remote_resolve: ""
          - remote_port: "443"
            dig_type: "A"
            remote_host: ""
            remote_resolve: "socks5_remote_resolve"
          - remote_port: ""
            dig_type: ""
            remote_host: "icanhazip.com:443"
            remote_resolve: "socks5_remote_resolve"
    uses: ./.github/workflows/test.yml
    with:
      remote_port: ${{ matrix.remote_port }}
      dig_type: ${{ matrix.dig_type }}
      remote_host: ${{ matrix.remote_host }}
      remote_resolve: ${{ matrix.remote_resolve }}